[pytest]
markers=
    smoke: Run to validate the system on high level
    regression: Run all the cases to ensure nothing is broken
    api: Validate API responses
    ui: To check how the UI app works

addopts= --tracing=retain-on-failure